version: "3"
services:
  mysql:
    image: mysql:5.7.22
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=holaperomasdificil
      - MYSQL_DATABASE=testing-panel
      - MYSQL_USER=testing-panel
      - MYSQL_PASSWORD=hola
      restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      - PMA_USER=testing-panel
      - PMA_PASSWORD=hola
    restart: always
